# Generated by Django 3.2.25 on 2024-10-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=2048)),
                ('main_image', models.ImageField(null=True, upload_to='image/products')),
                ('image1', models.ImageField(null=True, upload_to='image/products')),
                ('image2', models.ImageField(null=True, upload_to='image/products')),
                ('image3', models.ImageField(null=True, upload_to='image/products')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.category')),
                ('sizes', models.ManyToManyField(blank=True, null=True, to='tests.Size')),
            ],
        ),
    ]
