# Generated by Django 5.1 on 2024-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image/products'),
        ),
    ]
