# Generated by Django 5.1.4 on 2025-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
