# Generated by Django 5.1 on 2024-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_city_province_user_birth_date_address_city_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
